name: test 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: [1.16.3]
        otp: [25.3.2]

    steps:
    - uses: actions/checkout@v3

    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }} # Define the elixir version [required]
        otp-version: ${{ matrix.otp }} # Define the OTP version [required]

    - name: Retrieve Dependencies Cache
      uses: actions/cache@v2
      id: cache-elixir-deps #id to use in retrieve action
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

    - name: Install Dependencies
      if: steps.cache-elixir-deps.outputs.cache-hit != 'true'
      run: mix do deps.get, deps.compile, compile

    - name: Check Formatting
      run: mix format --check-formatted

    - name: Setup db
      run: mix ecto.reset

    - name: Run Tests
      run: mix coveralls.github

